name: Playwright Tests

on:
  pull_request:

jobs:
  wait_for_vercel:
    name: Wait for Vercel
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Setup Playwright
        run: npx playwright install-deps chromium
      - name: Install dependencies
        run: yarn install
      - name: Run E2E Tests on Netlify URL
        run: yarn e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ needs.wait_for_vercel.outputs.preview_url }}